version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
words:
  - allman
  - alloca
  - anthropics
  - architecting
  - arrayindex
  - arrayinsert
  - binop
  - bitflags
  - bytemuck
  - cairols
  - cairom
  - callees
  - casm
  - chrono
  - chumsky
  - clippy
  - cmark
  - codegen
  - combinators
  - csed
  - cstark
  - dashmap
  - dataclass
  - deque
  - dests
  - dhat
  - dtolnay
  - elems
  - enitrat
  - eprintln
  - evals
  - extractfield
  - extracttuple
  - filetime
  - foldl
  - foldr
  - framealloc
  - funcs
  - getelementptr
  - horizen
  - ilog
  - imma
  - immediates
  - indexmap
  - insertfield
  - inserttuple
  - insta
  - instrs
  - itertools
  - kats
  - kiro
  - kkrt
  - krate
  - logup
  - logups
  - lvalue
  - makefixedarray
  - makestruct
  - maketuple
  - mathrm
  - mdtest
  - merkle
  - mpsc
  - mult
  - mults
  - nocapture
  - nops
  - oneshot
  - operandless
  - peekable
  - pointee
  - preds
  # TODO: remove when stwo is updated
  - preproccessed
  - println
  - proptest
  - ranlib
  - repr
  - resx
  - rfib
  - rfind
  - rngs
  - rustc
  - rustflags
  - rustsec
  - rustup
  - samply
  - sbox
  - scalarizable
  - scalarization
  - scalarize
  - scalarized
  - scalarizing
  - seedable
  - serde
  - simply
  - smallvec
  - smol
  - softline
  - sreedhar
  - sroa
  - stackalloc
  - starkware
  - stdext
  - stwo
  - subexpression
  - subspan
  - succ
  - succs
  - swatinem
  - tempvar
  - thiserror
  - tlsv
  - toplevel
  - topo
  - torczon
  - treee
  - typechecks
  - upcasting
  - usize
  - unsuffixed
  - vulns
  - walkdir
  - womir
  - worktree
  - worktrees
  - yarnrc
  - ybool
  - zalsa
  - zeroable
  - zkhash
