[package]
name = "cairo-m-project"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tracing.workspace = true
tempfile.workspace = true
ignore = "0.4"
toml = "0.9.2"
