name: PR Benchmarks

on:
  pull_request:
    paths:
      - "crates/runner/**"
      - ".github/workflows/benchmark-pr.yml"

permissions:
  pull-requests: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Compare Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"

      - name: Run benchmarks
        run: |
          cd crates/runner
          cargo bench --bench vm_benchmark -- --output-format bencher | tee output.txt

      # Compare benchmarks with data from gh-pages
      - name: Compare benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Cairo-M VM Benchmarks
          tool: "cargo"
          output-file-path: crates/runner/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Use the same settings as main branch but without auto-push
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: "dev/bench"
          auto-push: false
          # Alert and comment configuration
          comment-on-alert: true
          alert-threshold: "105%"
          comment-always: true
          fail-on-alert: true
          fail-threshold: "200%"
          summary-always: true
